import mysql from "mysql2/promise"
import pg from "pg"
import { execFile } from "node:child_process"
import { promisify } from "node:util"
import { readFile } from "node:fs/promises"
const exec=promisify(execFile)
const sleep=ms=>new Promise(r=>setTimeout(r,ms))
const required=(v,n)=>{if(!v)throw Object.assign(new Error("Missing "+n),{code:"INVALID_PROVIDER_CONFIGURATION",retryable:false})}
const slug=v=>v.toLowerCase().replace(/[^a-z0-9-]+/g,"-").replace(/^-+|-+$/g,"").slice(0,48)||"tenant"
async function request(url,options={},timeout=30000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{...options,signal:c.signal});const text=await r.text();let b={};try{b=text?JSON.parse(text):{}}catch{b={raw:text.slice(0,1000)}}if(!r.ok){const e=new Error(b.message||b.error||"HTTP "+r.status);e.code="HTTP_"+r.status;e.retryable=[408,409,425,429,500,502,503,504].includes(r.status);throw e}return b}finally{clearTimeout(t)}}
function jsonSecret(input){const s=input.secret;if(!s||typeof s!=="object"||Array.isArray(s))throw Object.assign(new Error("Provider credentials are missing."),{code:"INVALID_PROVIDER_CONFIGURATION",retryable:false});return s}

class ConvexProvider{
 async api(path,input,options={}){const s=jsonSecret(input);required(s.managementToken,"Convex management token");required(s.teamId,"Convex team ID");return request("https://api.convex.dev/v1"+path,{...options,headers:{authorization:"Bearer "+s.managementToken,"content-type":"application/json",...(options.headers||{})}})}
 async create(input){const s=jsonSecret(input);if(input.reference&&s.deployKey)return {backendReference:input.reference,deployKey:s.deployKey,deploymentName:s.deploymentName,region:input.region||"default"};const d=await this.api("/teams/"+encodeURIComponent(s.teamId)+"/create_project",input,{method:"POST",body:JSON.stringify({projectName:"Jusclick · "+input.tenantSlug,deploymentType:"prod",deploymentRegion:input.region||undefined})});const ref=d.deploymentUrl||d.deployment?.url;const deploymentName=d.deploymentName||d.deployment?.name;required(ref,"Convex deployment URL");required(deploymentName,"Convex deployment name");const key=await request("https://api.convex.dev/v1/deployments/"+encodeURIComponent(deploymentName)+"/create_deploy_key",{method:"POST",headers:{authorization:"Bearer "+s.managementToken,"content-type":"application/json"},body:JSON.stringify({name:"jusclick-provisioner"})});const deployKey=key.deployKey||key.token||key.adminKey;required(deployKey,"Convex deploy key");return {backendReference:ref,deploymentName,deployKey,region:d.region||input.region||"default"}}
 async configure(r,input){required(input.tenantAuthIssuer,"Tenant auth issuer");for(const [k,v] of Object.entries({TENANT_AUTH_ISSUER:input.tenantAuthIssuer,TENANT_AUTH_APPLICATION_ID:"convex"}))await exec("../node_modules/.bin/convex",["env","set",k,String(v)],{cwd:"/app/tenant-template",env:{...process.env,CONVEX_DEPLOY_KEY:r.deployKey}});return r}
 async migrate(r){await exec("../node_modules/.bin/convex",["deploy"],{cwd:"/app/tenant-template",env:{...process.env,CONVEX_DEPLOY_KEY:r.deployKey},maxBuffer:20*1024*1024});return r}
 async bootstrap(r,input){const args=JSON.stringify({companyName:input.companyName,ownerSubject:input.ownerSubject||input.ownerEmail,ownerName:input.ownerName||input.ownerEmail,ownerEmail:input.ownerEmail});await exec("../node_modules/.bin/convex",["run","tenant:bootstrap",args],{cwd:"/app/tenant-template",env:{...process.env,CONVEX_DEPLOY_KEY:r.deployKey},maxBuffer:5*1024*1024});return r}
 async health(r){await exec("../node_modules/.bin/convex",["run","health:check","{}"],{cwd:"/app/tenant-template",env:{...process.env,CONVEX_DEPLOY_KEY:r.deployKey},maxBuffer:5*1024*1024});return {ok:true}}
 async provision(input,jobId,progress){let r=await progress("CREATING",null,await this.create(input));r=await progress("INITIALIZING",r,await this.configure(r,input));r=await progress("MIGRATING",r,await this.migrate(r,input));r=await progress("BOOTSTRAPPING",r,await this.bootstrap(r,input));await progress("VERIFYING",r,await this.health(r,input));return {backendReference:r.backendReference,region:r.region,schemaVersion:input.templateVersion||"1",deploymentName:r.deploymentName}}
}

class SupabaseProvider{
 async api(path,input,options={}){const s=jsonSecret(input);required(s.managementToken,"Supabase management token");return request("https://api.supabase.com"+path,{...options,headers:{authorization:"Bearer "+s.managementToken,"content-type":"application/json",...(options.headers||{})}})}
 async create(input){const s=jsonSecret(input);if(input.projectRef)return {projectRef:input.projectRef,backendReference:input.endpoint||"https://"+input.projectRef+".supabase.co",region:input.region||"eu-west-1",host:s.host||input.projectRef+".supabase.co"};required(s.organizationId,"Supabase organization ID");required(s.databasePassword,"Supabase database password");const d=await this.api("/v1/projects",input,{method:"POST",body:JSON.stringify({name:"jusclick-"+slug(input.tenantSlug),organization_id:s.organizationId,region:input.region||"eu-west-1",plan:s.plan||"free",database_password:s.databasePassword})});required(d.ref,"Supabase project reference");return {projectRef:d.ref,backendReference:d.api_url||"https://"+d.ref+".supabase.co",region:d.region||input.region||"eu-west-1",host:d.database?.host||s.host||d.ref+".supabase.co"}}
 async wait(r,input){for(let i=0;i<60;i++){const d=await this.api("/v1/projects/"+encodeURIComponent(r.projectRef),input);const st=String(d.status||d.health||"").toUpperCase();if(["ACTIVE_HEALTHY","ACTIVE","HEALTHY"].includes(st))return {...r,host:d.database?.host||r.host||r.projectRef+".supabase.co"};if(["FAILED","ERROR"].includes(st))throw new Error("Supabase project failed: "+st);await sleep(3000)}throw new Error("Supabase project readiness timed out.")}
 async migrate(r,input){const secret=jsonSecret(input);const sql=await readFile("/app/migrations/postgres/001_tenant.sql","utf8");const {Client}=pg;const c=new Client({host:r.host||r.projectRef+".supabase.co",port:5432,user:"postgres",password:secret.databasePassword,database:"postgres",ssl:{rejectUnauthorized:false}});await c.connect();try{await c.query(sql)}finally{await c.end()}return r}
 async configure(r,input){await this.api("/v1/projects/"+encodeURIComponent(r.projectRef)+"/config/auth",input,{method:"PATCH",body:JSON.stringify({site_url:r.backendReference,disable_signup:true})});return r}
 async bootstrap(r,input){const secret=jsonSecret(input);const {Client}=pg;const c=new Client({host:r.host||r.projectRef+".supabase.co",port:5432,user:"postgres",password:secret.databasePassword,database:"postgres",ssl:{rejectUnauthorized:false}});await c.connect();try{await c.query('INSERT INTO staff_profiles(subject,email,name,role,active) VALUES ($1,$2,$3,$4,TRUE) ON CONFLICT (subject) DO UPDATE SET email=EXCLUDED.email,name=EXCLUDED.name,role=EXCLUDED.role,active=TRUE',[input.ownerSubject||input.ownerEmail,input.ownerEmail,input.ownerName||input.ownerEmail,"TENANT_OWNER"])}finally{await c.end()}return r}
 async health(r,input){const secret=jsonSecret(input);const {Client}=pg;const c=new Client({host:r.host||r.projectRef+".supabase.co",port:5432,user:"postgres",password:secret.databasePassword,database:"postgres",ssl:{rejectUnauthorized:false}});await c.connect();try{await c.query("SELECT 1")}finally{await c.end()}return {ok:true}}
 async provision(input,jobId,progress){let r=await progress("CREATING",null,await this.create(input));r=await progress("WAITING_FOR_HEALTH",r,await this.wait(r,input));r=await progress("INITIALIZING",r,await this.configure(r,input));r=await progress("MIGRATING",r,await this.migrate(r,input));r=await progress("BOOTSTRAPPING",r,await this.bootstrap(r,input));await progress("VERIFYING",r,await this.health(r,input));return {backendReference:r.backendReference,region:r.region,schemaVersion:input.templateVersion||"1",projectRef:r.projectRef}}
}

class MySqlProvider{
 async create(input){const s=jsonSecret(input);required(s.host,"MySQL host");required(s.user,"MySQL user");required(s.password,"MySQL password");const name=input.databaseName||("jusclick_"+slug(input.tenantSlug).replace(/-/g,"_")+"_"+input.tenantId.replace(/[^a-zA-Z0-9]/g,"").slice(-12));const db=mysql.createPool({host:s.host,port:Number(s.port||3306),user:s.user,password:s.password,ssl:s.ssl?{rejectUnauthorized:false}:undefined,connectionLimit:3});try{await db.query("CREATE DATABASE IF NOT EXISTS "+name);return {databaseName:name,backendReference:input.endpoint||"mysql://"+s.host+":"+Number(s.port||3306)+"/"+name,region:input.region||"default"}}finally{await db.end()}}
 async wait(r){return r}
 async migrate(r,input){const secret=jsonSecret(input);const sql=await readFile("/app/migrations/mysql/001_tenant.sql","utf8");const db=mysql.createPool({host:secret.host,port:Number(secret.port||3306),user:secret.user,password:secret.password,database:r.databaseName,ssl:secret.ssl?{rejectUnauthorized:false}:undefined,connectionLimit:3,multipleStatements:true});try{await db.query(sql)}finally{await db.end()}return r}
 async bootstrap(r,input){const secret=jsonSecret(input);const db=mysql.createPool({host:secret.host,port:Number(secret.port||3306),user:secret.user,password:secret.password,database:r.databaseName,ssl:secret.ssl?{rejectUnauthorized:false}:undefined,connectionLimit:2});try{await db.query("INSERT IGNORE INTO staff_profiles(subject,email,name,role,active) VALUES (?,?,?,'TENANT_OWNER',TRUE)",[input.ownerSubject||input.ownerEmail,input.ownerEmail,input.ownerName||input.ownerEmail])}finally{await db.end()}return r}
 async health(r,input){const secret=jsonSecret(input);const db=mysql.createPool({host:secret.host,port:Number(secret.port||3306),user:secret.user,password:secret.password,database:r.databaseName,ssl:secret.ssl?{rejectUnauthorized:false}:undefined,connectionLimit:1});try{const [rows]=await db.query("SELECT 1 AS ok");if(!rows[0]?.ok)throw new Error("MySQL health check failed")}finally{await db.end()}return {ok:true}}
 async provision(input,jobId,progress){let r=await progress("CREATING",null,await this.create(input));r=await progress("WAITING_FOR_HEALTH",r,await this.wait(r));r=await progress("MIGRATING",r,await this.migrate(r,input));r=await progress("BOOTSTRAPPING",r,await this.bootstrap(r,input));await progress("VERIFYING",r,await this.health(r,input));return {backendReference:r.backendReference,region:r.region,schemaVersion:input.templateVersion||"1",databaseName:r.databaseName}}
}

export async function runProvision(input,jobId,progress){const p=input.provider==="convex"?new ConvexProvider():input.provider==="supabase"?new SupabaseProvider():input.provider==="mysql"?new MySqlProvider():null;if(!p)throw Object.assign(new Error("Unsupported provider"),{code:"UNSUPPORTED_PROVIDER",retryable:false});return p.provision(input,jobId,progress)}
